# TODO: REMOVE THESE PARAMETERS
USERNAME = 'chh'
PASSWD = 'chh2024'
HOST = 'localhost'
PORT = '3306'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWD}@{HOST}:{PORT}/chh'
SQLALCHEMY_TRACK_MODIFICATIONS = False